/**
 * menuIconCatalog — danh mục icon cho dropdown chọn icon của MenuManager (màn hình admin).
 *
 * ⚠️ LỊCH SỬ + LÝ DO (đo ngày 2026-09-21):
 * Bản cũ dùng `import * as FcIcons from "react-icons/fc"` rồi `Object.keys(FcIcons)` để liệt kê
 * MỌI icon. Namespace + Object.keys khiến Rollup KHÔNG thể tree-shake ⇒ phải giữ TOÀN BỘ các bộ
 * (md 4.341 + bi 1.634 + fa 1.611 + ai 789 + fc 329 icon). Vì các bộ này còn được nhiều module
 * khác dùng, module ĐẦY ĐỦ bị đưa vào chunk dùng chung ⇒ mọi page phải tải thêm ~2,5 MB icon
 * (react-icons/md 1.789 KB + 714 KB) và trước đó là 4,9 MB nằm thẳng trong entry chunk.
 *
 * Bản này dùng DANH SÁCH TINH TUYỂN + NAMED IMPORT ⇒ tree-shake hoạt động bình thường,
 * chunk chỉ còn những icon thực sự dùng. Picker vẫn đủ nhiều icon MÀU (Flat Color) và có nghĩa;
 * đổi lại không còn 9.860 icon trộn lẫn (thực tế gần như không dùng hết).
 *
 * 👉 Muốn thêm icon: thêm tên vào mảng tương ứng (tên phải tồn tại trong `react-icons/<bộ>`).
 *    Hoặc chạy lại `node scratch/gen-menu-icon-catalog.mjs` (file này được sinh tự động).
 */
import type { ComponentType } from "react";
import {
  FcFolder,
  FcOpenedFolder,
  FcAddressBook,
  FcAudioFile,
  FcBookmark,
  FcAcceptDatabase,
  FcAddDatabase,
  FcAreaChart,
  FcBusinessContact,
  FcCollaboration,
  FcConferenceCall,
  FcFactoryBreakdown,
  FcFactory,
  FcPackage,
  FcMoneyTransfer,
  FcRegisteredTrademark,
  FcSalesPerformance,
  FcAlarmClock,
  FcCalendar,
  FcClock,
  FcEngineering,
  FcFlowChart,
  FcParallelTasks,
  FcDatabase,
  FcDeleteDatabase,
  FcWiFiLogo,
  FcApproval,
  FcApprove,
  FcCheckmark,
  FcCustomerSupport,
  FcFeedback,
  FcInfo,
  FcBrokenLink,
  FcCellPhone,
  FcComments,
  FcBriefcase,
  FcBusiness,
  FcBusinessman,
  FcKey,
  FcLockLandscape,
  FcLockPortrait,
  FcClearFilters,
  FcEmptyFilter,
  FcFilledFilter,
  FcAddColumn,
  FcAddImage,
  FcAddRow,
  FcDiploma1,
  FcDiploma2,
  FcDocument,
  FcBarChart,
  FcCalculator,
  FcComboChart,
  FcContacts,
  FcManager,
  FcShop,
  FcStackOfPhotos,
  FcTrademark,
  FcLock,
  FcOvertime,
  FcTimeline,
  FcProcess,
  FcPuzzle,
  FcServices,
  FcDisapprove,
  FcFlashAuto,
  FcFlashOff,
  FcOnlineSupport,
  FcPrivacy,
  FcQuestions,
  FcIphone,
  FcLink,
  FcMultipleSmartphones,
  FcBusinesswoman,
  FcDepartment,
  FcHome,
  FcUnlock,
  FcGrid,
  FcList,
  FcSearch,
  FcBadDecision,
  FcCameraAddon,
  FcCameraIdentification,
  FcFile,
  FcImageFile,
  FcLibrary,
  FcDataBackup,
  FcDataConfiguration,
  FcDataEncryption,
  FcSettings,
  FcWorkflow,
  FcFlashOn,
  FcIdea,
  FcNoIdea,
  FcRules,
  FcSupport,
  FcSurvey,
  FcPhone,
  FcShare,
  FcSmartphoneTablet,
  FcOrgUnit,
  FcOrganization,
  FcTreeStructure,
  FcTodoList,
  FcViewDetails,
  FcCamera,
  FcCancel,
  FcCompactCamera,
  FcReadingEbook,
  FcTemplate,
} from "react-icons/fc";
import {
  MdCreateNewFolder,
  MdDriveFolderUpload,
  MdFolderCopy,
  MdBookOnline,
  MdBook,
  MdBookmarkAdd,
  MdAddchart,
  MdAnalytics,
  MdBarcodeReader,
  MdContactPage,
  MdContactSupport,
  MdGroupWork,
  MdAccountBox,
  MdAddShoppingCart,
  MdAllInbox,
  MdAccountBalanceWallet,
  MdCreditCardOff,
  MdCreditCard,
  MdAlarmAdd,
  MdAlarmOff,
  MdAlarmOn,
  MdAdminPanelSettings,
  MdBugReport,
  MdCodeOff,
  MdNetworkPing,
  MdPermScanWifi,
  MdTerminal,
  MdCardGiftcard,
  MdCheckCircleOutline,
  MdCheckCircle,
} from "react-icons/md";
import {
  BiFolderMinus,
  BiFolderOpen,
  BiFolderPlus,
  BiBookAdd,
  BiBookAlt,
  BiBookBookmark,
  BiBarChartAlt2,
  BiBarChartAlt,
  BiBarChartSquare,
  BiGroup,
  BiUserCheck,
  BiUserCircle,
  BiBox,
  BiCartAdd,
  BiCartAlt,
  BiCreditCardAlt,
  BiCreditCardFront,
  BiCreditCard,
  BiAlarmAdd,
  BiAlarmExclamation,
} from "react-icons/bi";

export interface MenuIconItem {
  name: string;
  library: string;
  IconComponent: ComponentType<any>;
}

/** Danh mục icon tinh tuyển (giữ nguyên shape cũ để MenuManager không phải sửa). */
export const MENU_ICON_ENTRIES: MenuIconItem[] = [
  { name: "FcFolder", library: "fc", IconComponent: FcFolder },
  { name: "FcOpenedFolder", library: "fc", IconComponent: FcOpenedFolder },
  { name: "FcAddressBook", library: "fc", IconComponent: FcAddressBook },
  { name: "FcAudioFile", library: "fc", IconComponent: FcAudioFile },
  { name: "FcBookmark", library: "fc", IconComponent: FcBookmark },
  { name: "FcAcceptDatabase", library: "fc", IconComponent: FcAcceptDatabase },
  { name: "FcAddDatabase", library: "fc", IconComponent: FcAddDatabase },
  { name: "FcAreaChart", library: "fc", IconComponent: FcAreaChart },
  { name: "FcBusinessContact", library: "fc", IconComponent: FcBusinessContact },
  { name: "FcCollaboration", library: "fc", IconComponent: FcCollaboration },
  { name: "FcConferenceCall", library: "fc", IconComponent: FcConferenceCall },
  { name: "FcFactoryBreakdown", library: "fc", IconComponent: FcFactoryBreakdown },
  { name: "FcFactory", library: "fc", IconComponent: FcFactory },
  { name: "FcPackage", library: "fc", IconComponent: FcPackage },
  { name: "FcMoneyTransfer", library: "fc", IconComponent: FcMoneyTransfer },
  { name: "FcRegisteredTrademark", library: "fc", IconComponent: FcRegisteredTrademark },
  { name: "FcSalesPerformance", library: "fc", IconComponent: FcSalesPerformance },
  { name: "FcAlarmClock", library: "fc", IconComponent: FcAlarmClock },
  { name: "FcCalendar", library: "fc", IconComponent: FcCalendar },
  { name: "FcClock", library: "fc", IconComponent: FcClock },
  { name: "FcEngineering", library: "fc", IconComponent: FcEngineering },
  { name: "FcFlowChart", library: "fc", IconComponent: FcFlowChart },
  { name: "FcParallelTasks", library: "fc", IconComponent: FcParallelTasks },
  { name: "FcDatabase", library: "fc", IconComponent: FcDatabase },
  { name: "FcDeleteDatabase", library: "fc", IconComponent: FcDeleteDatabase },
  { name: "FcWiFiLogo", library: "fc", IconComponent: FcWiFiLogo },
  { name: "FcApproval", library: "fc", IconComponent: FcApproval },
  { name: "FcApprove", library: "fc", IconComponent: FcApprove },
  { name: "FcCheckmark", library: "fc", IconComponent: FcCheckmark },
  { name: "FcCustomerSupport", library: "fc", IconComponent: FcCustomerSupport },
  { name: "FcFeedback", library: "fc", IconComponent: FcFeedback },
  { name: "FcInfo", library: "fc", IconComponent: FcInfo },
  { name: "FcBrokenLink", library: "fc", IconComponent: FcBrokenLink },
  { name: "FcCellPhone", library: "fc", IconComponent: FcCellPhone },
  { name: "FcComments", library: "fc", IconComponent: FcComments },
  { name: "FcBriefcase", library: "fc", IconComponent: FcBriefcase },
  { name: "FcBusiness", library: "fc", IconComponent: FcBusiness },
  { name: "FcBusinessman", library: "fc", IconComponent: FcBusinessman },
  { name: "FcKey", library: "fc", IconComponent: FcKey },
  { name: "FcLockLandscape", library: "fc", IconComponent: FcLockLandscape },
  { name: "FcLockPortrait", library: "fc", IconComponent: FcLockPortrait },
  { name: "FcClearFilters", library: "fc", IconComponent: FcClearFilters },
  { name: "FcEmptyFilter", library: "fc", IconComponent: FcEmptyFilter },
  { name: "FcFilledFilter", library: "fc", IconComponent: FcFilledFilter },
  { name: "FcAddColumn", library: "fc", IconComponent: FcAddColumn },
  { name: "FcAddImage", library: "fc", IconComponent: FcAddImage },
  { name: "FcAddRow", library: "fc", IconComponent: FcAddRow },
  { name: "FcDiploma1", library: "fc", IconComponent: FcDiploma1 },
  { name: "FcDiploma2", library: "fc", IconComponent: FcDiploma2 },
  { name: "FcDocument", library: "fc", IconComponent: FcDocument },
  { name: "FcBarChart", library: "fc", IconComponent: FcBarChart },
  { name: "FcCalculator", library: "fc", IconComponent: FcCalculator },
  { name: "FcComboChart", library: "fc", IconComponent: FcComboChart },
  { name: "FcContacts", library: "fc", IconComponent: FcContacts },
  { name: "FcManager", library: "fc", IconComponent: FcManager },
  { name: "FcShop", library: "fc", IconComponent: FcShop },
  { name: "FcStackOfPhotos", library: "fc", IconComponent: FcStackOfPhotos },
  { name: "FcTrademark", library: "fc", IconComponent: FcTrademark },
  { name: "FcLock", library: "fc", IconComponent: FcLock },
  { name: "FcOvertime", library: "fc", IconComponent: FcOvertime },
  { name: "FcTimeline", library: "fc", IconComponent: FcTimeline },
  { name: "FcProcess", library: "fc", IconComponent: FcProcess },
  { name: "FcPuzzle", library: "fc", IconComponent: FcPuzzle },
  { name: "FcServices", library: "fc", IconComponent: FcServices },
  { name: "FcDisapprove", library: "fc", IconComponent: FcDisapprove },
  { name: "FcFlashAuto", library: "fc", IconComponent: FcFlashAuto },
  { name: "FcFlashOff", library: "fc", IconComponent: FcFlashOff },
  { name: "FcOnlineSupport", library: "fc", IconComponent: FcOnlineSupport },
  { name: "FcPrivacy", library: "fc", IconComponent: FcPrivacy },
  { name: "FcQuestions", library: "fc", IconComponent: FcQuestions },
  { name: "FcIphone", library: "fc", IconComponent: FcIphone },
  { name: "FcLink", library: "fc", IconComponent: FcLink },
  { name: "FcMultipleSmartphones", library: "fc", IconComponent: FcMultipleSmartphones },
  { name: "FcBusinesswoman", library: "fc", IconComponent: FcBusinesswoman },
  { name: "FcDepartment", library: "fc", IconComponent: FcDepartment },
  { name: "FcHome", library: "fc", IconComponent: FcHome },
  { name: "FcUnlock", library: "fc", IconComponent: FcUnlock },
  { name: "FcGrid", library: "fc", IconComponent: FcGrid },
  { name: "FcList", library: "fc", IconComponent: FcList },
  { name: "FcSearch", library: "fc", IconComponent: FcSearch },
  { name: "FcBadDecision", library: "fc", IconComponent: FcBadDecision },
  { name: "FcCameraAddon", library: "fc", IconComponent: FcCameraAddon },
  { name: "FcCameraIdentification", library: "fc", IconComponent: FcCameraIdentification },
  { name: "FcFile", library: "fc", IconComponent: FcFile },
  { name: "FcImageFile", library: "fc", IconComponent: FcImageFile },
  { name: "FcLibrary", library: "fc", IconComponent: FcLibrary },
  { name: "FcDataBackup", library: "fc", IconComponent: FcDataBackup },
  { name: "FcDataConfiguration", library: "fc", IconComponent: FcDataConfiguration },
  { name: "FcDataEncryption", library: "fc", IconComponent: FcDataEncryption },
  { name: "FcSettings", library: "fc", IconComponent: FcSettings },
  { name: "FcWorkflow", library: "fc", IconComponent: FcWorkflow },
  { name: "FcFlashOn", library: "fc", IconComponent: FcFlashOn },
  { name: "FcIdea", library: "fc", IconComponent: FcIdea },
  { name: "FcNoIdea", library: "fc", IconComponent: FcNoIdea },
  { name: "FcRules", library: "fc", IconComponent: FcRules },
  { name: "FcSupport", library: "fc", IconComponent: FcSupport },
  { name: "FcSurvey", library: "fc", IconComponent: FcSurvey },
  { name: "FcPhone", library: "fc", IconComponent: FcPhone },
  { name: "FcShare", library: "fc", IconComponent: FcShare },
  { name: "FcSmartphoneTablet", library: "fc", IconComponent: FcSmartphoneTablet },
  { name: "FcOrgUnit", library: "fc", IconComponent: FcOrgUnit },
  { name: "FcOrganization", library: "fc", IconComponent: FcOrganization },
  { name: "FcTreeStructure", library: "fc", IconComponent: FcTreeStructure },
  { name: "FcTodoList", library: "fc", IconComponent: FcTodoList },
  { name: "FcViewDetails", library: "fc", IconComponent: FcViewDetails },
  { name: "FcCamera", library: "fc", IconComponent: FcCamera },
  { name: "FcCancel", library: "fc", IconComponent: FcCancel },
  { name: "FcCompactCamera", library: "fc", IconComponent: FcCompactCamera },
  { name: "FcReadingEbook", library: "fc", IconComponent: FcReadingEbook },
  { name: "FcTemplate", library: "fc", IconComponent: FcTemplate },
  { name: "MdCreateNewFolder", library: "md", IconComponent: MdCreateNewFolder },
  { name: "MdDriveFolderUpload", library: "md", IconComponent: MdDriveFolderUpload },
  { name: "MdFolderCopy", library: "md", IconComponent: MdFolderCopy },
  { name: "MdBookOnline", library: "md", IconComponent: MdBookOnline },
  { name: "MdBook", library: "md", IconComponent: MdBook },
  { name: "MdBookmarkAdd", library: "md", IconComponent: MdBookmarkAdd },
  { name: "MdAddchart", library: "md", IconComponent: MdAddchart },
  { name: "MdAnalytics", library: "md", IconComponent: MdAnalytics },
  { name: "MdBarcodeReader", library: "md", IconComponent: MdBarcodeReader },
  { name: "MdContactPage", library: "md", IconComponent: MdContactPage },
  { name: "MdContactSupport", library: "md", IconComponent: MdContactSupport },
  { name: "MdGroupWork", library: "md", IconComponent: MdGroupWork },
  { name: "MdAccountBox", library: "md", IconComponent: MdAccountBox },
  { name: "MdAddShoppingCart", library: "md", IconComponent: MdAddShoppingCart },
  { name: "MdAllInbox", library: "md", IconComponent: MdAllInbox },
  { name: "MdAccountBalanceWallet", library: "md", IconComponent: MdAccountBalanceWallet },
  { name: "MdCreditCardOff", library: "md", IconComponent: MdCreditCardOff },
  { name: "MdCreditCard", library: "md", IconComponent: MdCreditCard },
  { name: "MdAlarmAdd", library: "md", IconComponent: MdAlarmAdd },
  { name: "MdAlarmOff", library: "md", IconComponent: MdAlarmOff },
  { name: "MdAlarmOn", library: "md", IconComponent: MdAlarmOn },
  { name: "MdAdminPanelSettings", library: "md", IconComponent: MdAdminPanelSettings },
  { name: "MdBugReport", library: "md", IconComponent: MdBugReport },
  { name: "MdCodeOff", library: "md", IconComponent: MdCodeOff },
  { name: "MdNetworkPing", library: "md", IconComponent: MdNetworkPing },
  { name: "MdPermScanWifi", library: "md", IconComponent: MdPermScanWifi },
  { name: "MdTerminal", library: "md", IconComponent: MdTerminal },
  { name: "MdCardGiftcard", library: "md", IconComponent: MdCardGiftcard },
  { name: "MdCheckCircleOutline", library: "md", IconComponent: MdCheckCircleOutline },
  { name: "MdCheckCircle", library: "md", IconComponent: MdCheckCircle },
  { name: "BiFolderMinus", library: "bi", IconComponent: BiFolderMinus },
  { name: "BiFolderOpen", library: "bi", IconComponent: BiFolderOpen },
  { name: "BiFolderPlus", library: "bi", IconComponent: BiFolderPlus },
  { name: "BiBookAdd", library: "bi", IconComponent: BiBookAdd },
  { name: "BiBookAlt", library: "bi", IconComponent: BiBookAlt },
  { name: "BiBookBookmark", library: "bi", IconComponent: BiBookBookmark },
  { name: "BiBarChartAlt2", library: "bi", IconComponent: BiBarChartAlt2 },
  { name: "BiBarChartAlt", library: "bi", IconComponent: BiBarChartAlt },
  { name: "BiBarChartSquare", library: "bi", IconComponent: BiBarChartSquare },
  { name: "BiGroup", library: "bi", IconComponent: BiGroup },
  { name: "BiUserCheck", library: "bi", IconComponent: BiUserCheck },
  { name: "BiUserCircle", library: "bi", IconComponent: BiUserCircle },
  { name: "BiBox", library: "bi", IconComponent: BiBox },
  { name: "BiCartAdd", library: "bi", IconComponent: BiCartAdd },
  { name: "BiCartAlt", library: "bi", IconComponent: BiCartAlt },
  { name: "BiCreditCardAlt", library: "bi", IconComponent: BiCreditCardAlt },
  { name: "BiCreditCardFront", library: "bi", IconComponent: BiCreditCardFront },
  { name: "BiCreditCard", library: "bi", IconComponent: BiCreditCard },
  { name: "BiAlarmAdd", library: "bi", IconComponent: BiAlarmAdd },
  { name: "BiAlarmExclamation", library: "bi", IconComponent: BiAlarmExclamation },
];

export const getAllIcons = (): MenuIconItem[] => MENU_ICON_ENTRIES;
