import { COMPONENT_DATA } from "../../../rnd/interfaces/rndInterface";

export const DEFAULT_COMPONENT_LIST: COMPONENT_DATA[] = [
  {
    G_CODE_MAU: "123456",
    DOITUONG_NO: 5,
    DOITUONG_NAME: "Rectangle",
    PHANLOAI_DT: "CONTAINER",
    DOITUONG_STT: "A6",
    CAVITY_PRINT: 2,
    GIATRI: "AZ:4Z99ADOEBRABHKDMAG5UZUWF5Y",
    FONT_NAME: "Arial",
    FONT_SIZE: 6,
    FONT_STYLE: "B",
    POS_X: 0,
    POS_Y: 0,
    SIZE_W: 23,
    SIZE_H: 28.6,
    ROTATE: 0,
    REMARK: "remark",
  },
  {
    G_CODE_MAU: "123456",
    DOITUONG_NO: 0,
    DOITUONG_NAME: "Code name",
    PHANLOAI_DT: "TEXT",
    DOITUONG_STT: "A0",
    CAVITY_PRINT: 2,
    GIATRI: "GH68-54619A",
    FONT_NAME: "Arial",
    FONT_SIZE: 6,
    FONT_STYLE: "B",
    POS_X: 2.26,
    POS_Y: 20.53,
    SIZE_W: 2.08,
    SIZE_H: 2.08,
    ROTATE: 0,
    REMARK: "remark",
  },
  {
    G_CODE_MAU: "123456",
    DOITUONG_NO: 1,
    DOITUONG_NAME: "Model",
    PHANLOAI_DT: "TEXT",
    DOITUONG_STT: "A1",
    CAVITY_PRINT: 2,
    GIATRI: "SM-R910NZAAXJP",
    FONT_NAME: "Arial",
    FONT_SIZE: 6,
    FONT_STYLE: "B",
    POS_X: 2.26,
    POS_Y: 15.36,
    SIZE_W: 2.08,
    SIZE_H: 2.08,
    ROTATE: 0,
    REMARK: "remark",
  },
  {
    G_CODE_MAU: "123456",
    DOITUONG_NO: 1,
    DOITUONG_NAME: "EAN No 1",
    PHANLOAI_DT: "TEXT",
    DOITUONG_STT: "A2",
    CAVITY_PRINT: 2,
    GIATRI: "4986773220257",
    FONT_NAME: "Arial",
    FONT_SIZE: 6,
    FONT_STYLE: "B",
    POS_X: 2.26,
    POS_Y: 17.97,
    SIZE_W: 2.08,
    SIZE_H: 2.08,
    ROTATE: 0,
    REMARK: "remark",
  },
  {
    G_CODE_MAU: "123456",
    DOITUONG_NO: 4,
    DOITUONG_NAME: "Logo AMZ 1",
    PHANLOAI_DT: "IMAGE",
    DOITUONG_STT: "A3",
    CAVITY_PRINT: 2,
    GIATRI: "https://cmsvina4285.com/images/logoAMAZON.png",
    FONT_NAME: "Arial",
    FONT_SIZE: 6,
    FONT_STYLE: "B",
    POS_X: 2.28,
    POS_Y: 2.58,
    SIZE_W: 7.11,
    SIZE_H: 7,
    ROTATE: 0,
    REMARK: "remark",
  },
  {
    G_CODE_MAU: "123456",
    DOITUONG_NO: 5,
    DOITUONG_NAME: "Barcode 1",
    PHANLOAI_DT: "1D BARCODE",
    DOITUONG_STT: "A4",
    CAVITY_PRINT: 2,
    GIATRI: "GH68-55104A",
    FONT_NAME: "Arial",
    FONT_SIZE: 6,
    FONT_STYLE: "B",
    POS_X: 1.97,
    POS_Y: 23.57,
    SIZE_W: 19.05,
    SIZE_H: 3.55,
    ROTATE: 0,
    REMARK: "remark",
  },
  {
    G_CODE_MAU: "123456",
    DOITUONG_NO: 5,
    DOITUONG_NAME: "Matrix 1",
    PHANLOAI_DT: "2D MATRIX",
    DOITUONG_STT: "A5",
    CAVITY_PRINT: 2,
    GIATRI: "AZ:4Z99ADOEBRABHKDMAG5UZUWF5Y",
    FONT_NAME: "Arial",
    FONT_SIZE: 6,
    FONT_STYLE: "B",
    POS_X: 12,
    POS_Y: 2,
    SIZE_W: 9,
    SIZE_H: 9,
    ROTATE: 0,
    REMARK: "remark",
  },
];
