import React from "react";
import {
  renderTruncated,
  renderMono,
  renderRightNum,
  renderLotHighlight,
  renderVendorLot,
  renderUseYn,
  renderQcPass,
  renderCloseStatus,
} from "./failingCellRenderers";

export const getFailingColumns = () => [
  { field: "FAIL_ID", headerName: "FAIL_ID", resizable: true, width: 50, checkboxSelection: true, headerCheckboxSelection: true, cellRenderer: (p: any) => renderMono(p.value, "text-slate-800 font-semibold") },
  { field: "FACTORY", headerName: "FACTORY", resizable: true, width: 50, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "PLAN_ID_SUDUNG", headerName: "PLAN_ID_SUDUNG", resizable: true, width: 90, cellRenderer: (p: any) => renderMono(p.value, "text-blue-700 font-bold") },
  { field: "G_CODE", headerName: "G_CODE", resizable: true, width: 50, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "G_NAME", headerName: "G_NAME", resizable: true, width: 100, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "LIEUQL_SX", headerName: "LIEUQL_SX", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "MAKER", headerName: "MAKER", resizable: true, width: 60, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "M_CODE", headerName: "M_CODE", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value, "text-blue-600 font-semibold") },
  { field: "M_LOT_NO", headerName: "M_LOT_NO", resizable: true, width: 60, cellRenderer: (p: any) => renderLotHighlight(p.value, p.data?.QC_PASS === "Y") },
  { field: "VENDOR_LOT", headerName: "VENDOR_LOT", resizable: true, width: 70, cellRenderer: (p: any) => renderVendorLot(p.value, Boolean(p.data?.OUT2_EMPL)) },
  { field: "PROCESS_LOT_NO", headerName: "LOT_SX", resizable: true, width: 70, cellRenderer: (p: any) => renderMono(p.value, "font-bold text-slate-800") },
  {
    field: "M_NAME",
    headerName: "M_NAME",
    resizable: true,
    width: 80,
    cellRenderer: (p: any) => (
      <span className={`cell-truncate font-bold ${p.data?.IN2_EMPL ? "text-blue-600" : "text-rose-600"}`} title={p.value}>
        {p.value || "-"}
      </span>
    ),
  },
  { field: "WIDTH_CD", headerName: "WIDTH_CD", resizable: true, width: 60, cellRenderer: (p: any) => renderRightNum(p.value) },
  { field: "ROLL_QTY", headerName: "ROLL_QTY", resizable: true, width: 60, cellRenderer: (p: any) => renderRightNum(p.value) },
  { field: "TOTAL_IN_QTY", headerName: "TOTAL_IN_QTY", resizable: true, width: 80, cellRenderer: (p: any) => renderRightNum(p.data?.TOTAL_IN_QTY, "text-blue-700 font-bold") },
  { field: "SX_DEFECT", headerName: "SX_DEFECT", resizable: true, width: 80, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "OUT_DATE", headerName: "OUT_DATE", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "PHANLOAI", headerName: "PHANLOAI", resizable: true, width: 60, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "USE_YN", headerName: "USE_YN", resizable: true, width: 40, cellRenderer: (p: any) => renderUseYn(p.data?.USE_YN === "Y") },
  { field: "QC_PASS", headerName: "QC_PASS/FAIL", resizable: true, width: 70, cellRenderer: (p: any) => renderQcPass(p.data?.QC_PASS) },
  { field: "PROCESS_STATUS", headerName: "CLOSE_STATUS", resizable: true, width: 80, cellRenderer: (p: any) => renderCloseStatus(p.data?.PROCESS_STATUS) },
  { field: "QC_PASS_EMPL", headerName: "QC_PASS_EMPL", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "QC_PASS_DATE", headerName: "QC_PASS_DATE", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "PROCESS_EMPL", headerName: "PROCESS_EMPL", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "PROCESS_DATE", headerName: "PROCESS_DATE", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "IN1_EMPL", headerName: "IN1_EMPL", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "IN2_EMPL", headerName: "IN2_EMPL", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "OUT1_EMPL", headerName: "OUT1_EMPL", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "OUT2_EMPL", headerName: "OUT2_EMPL", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "REMARK", headerName: "REMARK", resizable: true, width: 60, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "IN_CUST_CD", headerName: "IN_CUST_CD", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "OUT_CUST_CD", headerName: "OUT_CUST_CD", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "IN_CUST_NAME", headerName: "IN_CUST_NAME", resizable: true, width: 80, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "OUT_CUST_NAME", headerName: "OUT_CUST_NAME", resizable: true, width: 90, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "OUT_PLAN_ID", headerName: "OUT_PLAN_ID", resizable: true, width: 70, cellRenderer: (p: any) => renderMono(p.value, "text-amber-700 font-bold") },
  { field: "REMARK_OUT", headerName: "REMARK_OUT", resizable: true, width: 80, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "NCR_ID", headerName: "NCR_ID", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value, "text-rose-600 font-bold") },
  { field: "PQC3_ID", headerName: "PQC3_ID", resizable: true, width: 60, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "DEFECT_PHENOMENON", headerName: "DEFECT_PHENOMENON", resizable: true, width: 120, cellRenderer: (p: any) => renderTruncated(p.value) },
  { field: "INS_EMPL", headerName: "INS_EMPL", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "INS_DATE", headerName: "INS_DATE", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "UPD_EMPL", headerName: "UPD_EMPL", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
  { field: "UPD_DATE", headerName: "UPD_DATE", resizable: true, width: 80, cellRenderer: (p: any) => renderMono(p.value) },
];
